######################################################################
# Automatically generated by qmake (2.00a) Tue Mar 7 13:22:36 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += . /usr/local/include/marsyas/
unix:LIBS += -lmarsyas -L/usr/local/lib
LIBS += -lm

# Input
HEADERS += Marx2DGraph.h Marx2DStackedGraphs.h
SOURCES += main.cpp Marx2DGraph.cpp Marx2DStackedGraphs.cpp
