#ifndef MEAWS_DEFS_H
#define MEAWS_DEFS_H

#define TEST_NONE 0
#define TEST_INTONATION 1
#define TEST_CONTROL 2

#define MEAWS_READY_NOTHING 1
#define MEAWS_READY_USER 2
#define MEAWS_READY_EXERCISE 3
#define MEAWS_READY_AUDIO 4

#endif

