/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.uvic.marsyas;

public class Map_String_MarControlPtr {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Map_String_MarControlPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Map_String_MarControlPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      marsyasJNI.delete_Map_String_MarControlPtr(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Map_String_MarControlPtr() {
    this(marsyasJNI.new_Map_String_MarControlPtr__SWIG_0(), true);
  }

  public Map_String_MarControlPtr(Map_String_MarControlPtr arg0) {
    this(marsyasJNI.new_Map_String_MarControlPtr__SWIG_1(Map_String_MarControlPtr.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return marsyasJNI.Map_String_MarControlPtr_size(swigCPtr, this);
  }

  public boolean empty() {
    return marsyasJNI.Map_String_MarControlPtr_empty(swigCPtr, this);
  }

  public void clear() {
    marsyasJNI.Map_String_MarControlPtr_clear(swigCPtr, this);
  }

  public MarControlPtr get(String key) {
    return new MarControlPtr(marsyasJNI.Map_String_MarControlPtr_get(swigCPtr, this, key), false);
  }

  public void set(String key, MarControlPtr x) {
    marsyasJNI.Map_String_MarControlPtr_set(swigCPtr, this, key, MarControlPtr.getCPtr(x), x);
  }

  public void del(String key) {
    marsyasJNI.Map_String_MarControlPtr_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return marsyasJNI.Map_String_MarControlPtr_has_key(swigCPtr, this, key);
  }

}
