/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.uvic.marsyas;

public class Vector_String {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Vector_String(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Vector_String obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      marsyasJNI.delete_Vector_String(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Vector_String() {
    this(marsyasJNI.new_Vector_String__SWIG_0(), true);
  }

  public Vector_String(long n) {
    this(marsyasJNI.new_Vector_String__SWIG_1(n), true);
  }

  public long size() {
    return marsyasJNI.Vector_String_size(swigCPtr, this);
  }

  public long capacity() {
    return marsyasJNI.Vector_String_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    marsyasJNI.Vector_String_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return marsyasJNI.Vector_String_isEmpty(swigCPtr, this);
  }

  public void clear() {
    marsyasJNI.Vector_String_clear(swigCPtr, this);
  }

  public void add(String x) {
    marsyasJNI.Vector_String_add(swigCPtr, this, x);
  }

  public String get(int i) {
    return marsyasJNI.Vector_String_get(swigCPtr, this, i);
  }

  public void set(int i, String val) {
    marsyasJNI.Vector_String_set(swigCPtr, this, i, val);
  }

}
