#####################################################################
# Automatically generated by qmake (2.00a) Sun Sep 4 17:57:49 2005
######################################################################

TEMPLATE = app
VERSION = 0.0.0
TARGET += 
DEPENDPATH += .
INCLUDEPATH += /usr/local/include/marsyas
unix:LIBS += -lmarsyas -L/usr/local/lib -lmad -lasound
# Input
HEADERS += MarGrid.h MarSystemWrapper.h MarGridWindow.h
SOURCES += main.cpp MarGrid.cpp MarSystemWrapper.cpp MarGridWindow.cpp
