/* marsyas/config.h.  Generated by configure.  */
/* marsyas/config.h.in.  Generated from configure.in by autoheader.  */

/* WINDOWS STUFF */
/* #undef CYGWIN */

/* Enable mad mp3 decoding */
/* #undef MAD_MP3 */

/* Enable Marsyas Assertions */
/* #undef MRSASSERTE */

/* Enable Marsyas Diagnostics */
/* #undef MRSDIAGNOSTIC */

/* Enable Marsyas Warnings */
/* #undef MRSWARNING */

/* Name of package */
#define PACKAGE "marsyas"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "gtzan@cs.uvic.ca"

/* Define to the full name of this package. */
#define PACKAGE_NAME "marsyas"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "marsyas 0.2.6"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "marsyas"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.2.6"

/* Version number of package */
#define VERSION "0.2.6"

/* IS BIG ENDINA */
/* #undef __BIG_ENDIAN__ */

/* CYGWIN FOR THREAD STUFF */
/* #undef __CYGWIN__ */

/* LINUX SYSTEM FOR RTAUDIO */
#define __LINUX_ALSASEQ__ 1

/* LINUX SYSTEM FOR RTAUDIO */
#define __LINUX_ALSA__ 1

/* LINUX SYSTEM FOR RTAUDIO */
/* #undef __LINUX_OSS__ */

/* MACOSX SYSTEM FOR RTAUDIO */
/* #undef __MACOSX_CORE__ */

/* LINUX STUFF */
#define __OS_LINUX__ 1

/* MACOSX STUFF */
/* #undef __OS_MACOSX__ */

/* WINDOWS SYSTEM FOR RTMIDI */
/* #undef __OS_WINDOWS__RTMIDI__ */

/* WINDOWS SYSTEM FOR RTAUDIO */
/* #undef __WINDOWS_DS__ */

/* WINDOWS SYSTEM FOR RTAUDIO */
/* #undef __WINDOWS_MM__ */

/* Enable readline */
/* #undef __WITHREADLINE__ */
