/* marsyas/config.h.  Generated by configure.  */
/* marsyas/config.h.in.  Generated from configure.in by autoheader.  */

/* WINDOWS STUFF */
/* #undef CYGWIN */

/* Enable mad mp3 decoding */
/* #define MAD_MP3 1 */ 

/* Root directory of Marsyas files */
#define MARSYAS_MFDIR "/usr/local/share/marsyas/mf"

/* Enable Marsyas Assertions */
 #define MRSASSERTE 1

/* Enable Marsyas Diagnostics */
/* #undef MRSDIAGNOSTIC */

/* Name of package */
#define PACKAGE "marsyas"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "gtzan@cs.uvic.ca"

/* Define to the full name of this package. */
#define PACKAGE_NAME "marsyas"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "marsyas 0.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "marsyas"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.2"

/* Version number of package */
#define VERSION "0.2"

/* Defined if on Win32 platform */
/* #undef WIN32 */

/* IS BIG ENDINA */
/* #undef __BIG_ENDIAN__ */

/* CYGWIN FOR THREAD STUFF */
/* #undef __CYGWIN__ */

/* LINUX SYSTEM FOR RTAUDIO */
/* #undef __LINUX_OSS__ 1 */ 

/* MACOSX SYSTEM FOR RTAUDIO */
/* #undef __MACOSX_CORE__ */

/* LINUX STUFF */
/* #define __OS_LINUX__ 1 */ 

/* MACOSX STUFF */
/* #undef __OS_MACOSX__ */

/* WINDOWS DIRECTSHOW SYSTEM FOR RTAUDIO */
#define __WINDOWS_DS__ 

/* WINDOWS ASIO SYSTEM FOR RTAUDIO */
//#define __WINDOWS_ASIO__ 

/* WINDOWS SYSTEM FOR RTMIDI  */  
#define __WINDOWS_MM__

/* READLINE SUPPORT */
#define __WITHREADLINE__ 1
