/* marsyas/config.h.  Generated by configure.  */
/* marsyas/config.h.in.  Generated from configure.in by autoheader.  */

/* WINDOWS STUFF */
/* #undef MARSYAS_CYGWIN */

/* Enable mad mp3 decoding */
/* #undef MARSYAS_MAD */

/* Enable Marsyas Assertions */
/* #undef MARSYAS_ASSERT */

/* Enable Audio IO */
//#define MARSYAS_AUDIOIO 1

/* Enable DEBUG MESSAGES */
/* #undef MARSYAS_DEBUG */

/* Enable Marsyas Diagnostics */
/* #undef MARSYAS_DIAGNOSTIC */

/* Enable MIDI IO */
//#define MARSYAS_MIDIIO 1

/* Enable Marsyas Warnings */
/* #define MARSYAS_WARNING 1 */

/* Enable ogg vorbis decoding */
/* #undef MARSYAS_OGG */

/* Name of package */
#define PACKAGE "marsyas"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "gtzan@cs.uvic.ca"

/* Define to the full name of this package. */
#define PACKAGE_NAME "marsyas"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "marsyas 0.2.9"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "marsyas"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.2.9"

/* Version number of package */
#define VERSION "0.2.9"

/* IS BIG ENDINA */
/* #undef MARSYAS_BIGENDIAN */

/* MARSYAS_CYGWIN FOR THREAD STUFF */
/* #undef MARSYAS_CYGWIN */

/* LINUX SYSTEM FOR RTAUDIO */
/* #define __LINUX_ALSASEQ__ 1 */

/* LINUX SYSTEM FOR RTAUDIO */
/* #define __LINUX_ALSA__ 1 */

/* LINUX SYSTEM FOR RTAUDIO */
/* #undef __LINUX_OSS__ */

/* MACOSX SYSTEM FOR RTAUDIO */
/* #undef __MACOSX_CORE__ */

/* LINUX STUFF */
/* #define MARSYAS_CYGWIN 1 */

/* MACOSX STUFF */
/* #undef MARSYAS_MACOSX */

/* WINDOWS SYSTEM FOR RTMIDI */
//#define MARSYAS_WIN32RTMIDI__

/* WINDOWS SYSTEM FOR RTAUDIO */
//#define __WINDOWS_DS__ 

/* WINDOWS SYSTEM FOR RTAUDIO */
//#define __WINDOWS_MM__

/* Enable readline */
/* #undef MARSYAS_READLINE */
