/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.uvic.marsyas;

public class MarSystem {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MarSystem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MarSystem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      marsyasJNI.delete_MarSystem(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void tick() {
    marsyasJNI.MarSystem_tick(swigCPtr, this);
  }

  public void update() {
    marsyasJNI.MarSystem_update(swigCPtr, this);
  }

  public void addMarSystem(MarSystem msys) {
    marsyasJNI.MarSystem_addMarSystem(swigCPtr, this, MarSystem.getCPtr(msys), msys);
  }

  public String getType() {
    return marsyasJNI.MarSystem_getType(swigCPtr, this);
  }

  public String getName() {
    return marsyasJNI.MarSystem_getName(swigCPtr, this);
  }

  public String getPrefix() {
    return marsyasJNI.MarSystem_getPrefix(swigCPtr, this);
  }

  public void setControl(String arg0, MarControlPtr arg1) {
    marsyasJNI.MarSystem_setControl(swigCPtr, this, arg0, MarControlPtr.getCPtr(arg1), arg1);
  }

  public void updControl(String arg0, MarControlPtr arg1) {
    marsyasJNI.MarSystem_updControl(swigCPtr, this, arg0, MarControlPtr.getCPtr(arg1), arg1);
  }

  public MarControlPtr getControl(String arg0) {
    return new MarControlPtr(marsyasJNI.MarSystem_getControl(swigCPtr, this, arg0), true);
  }

  public boolean hasControl(String arg0) {
    return marsyasJNI.MarSystem_hasControl(swigCPtr, this, arg0);
  }

  public void linkControl(String arg0, String arg1) {
    marsyasJNI.MarSystem_linkControl(swigCPtr, this, arg0, arg1);
  }

  public Map_String_MarControlPtr getControls() {
    return new Map_String_MarControlPtr(marsyasJNI.MarSystem_getControls(swigCPtr, this), true);
  }

}
