@node Interoperability
@chapter Interoperability

FIXME:   this will be junked soon.  -gp

Intro text

@menu
* Audio and MIDI::              
* WEKA::                        
* MATLAB::                      
* Python::                      
* OCaml::                       
@end menu


@node Audio and MIDI
@section Audio and MIDI

@itemize @bullet
@item
@strong{RtAudio}: Multiplatform C++ API for realtime audio input/output 

@itemize @minus
@item Linux (native ALSA, JACK, and OSS) 
@item MacOSX@copyright{}
@item Windows@copyright{} (DirectSound@copyright{} and ASIO@copyright{}) 
@item SGI@copyright{} 
@end itemize

@item
@strong{RtMIDI}: Multiplatform C++ API for realtime MIDI input/output 

@itemize @minus
@item Linux (ALSA) 
@item MacOSX@copyright{} 
@item Windows@copyright{}
@item SGI@copyright{}
@end itemize

@end itemize

@uref{http://www.music.mcgill.ca/~gary/rtaudio/}

@uref{http://www.music.mcgill.ca/~gary/rtmidi/}



@c @n ode Open Sound Control (OSC)
@c @s ection Open Sound Control (OSC)



@node WEKA
@section WEKA

It @emph{can} be done; read the source code.

@node MATLAB
@section MATLAB

MATLAB is a general blurb and whatnot.

@subheading Marsyas -> MATLAB

To export data from Marsyas into MATLAB, simply add

@example
DOCME code here
@end example

@noindent
to your .cpp source file, and

@example
DOCME code here
@end example

@noindent
to your MATLAB file.


@subheading Marsyas <- MATLAB

To import data into Marsyas from MATLAB, simply add

@example
DOCME code here
@end example

@noindent
to your .cpp source file, and

@example
DOCME code here
@end example

@noindent
to your MATLAB file.


@node Python
@section Python

It @emph{can} be done; read the source code.

@node OCaml
@section OCaml

To combine Marsyas and OCaml, see the MarsyasOCaml documentation at
@uref{http://www.cs.uvic.ca/~inb/work/marsyasOCaml/}


