@node Automatic testing
@chapter Automatic testing

In an attempt to reduce the number of times we break working code, we
have added some testing mechanisms to Marsyas.

@menu
* Regression tests::            
* Daily Auto-tester::           
@end menu


@node Regression tests
@section Regression tests

These tests are deliberately simple and easy to understand.

@menu
* What does regression mean?::  
* How do the tests work?::      
* Where is addSource() and addDest() defined?::  
* When a test fails...::        
* Why should I care?::          
* They won't work!::            
@end menu

@node What does regression mean?
@subsection What does "regression" mean?


@node How do the tests work?
@subsection How do the tests work?


@node Where is addSource() and addDest() defined?
@subsection Where is addSource() and addDest() defined?


@node When a test fails...
@subsection When a test fails...



@node Why should I care?
@subsection  Why should I care?



@node They won't work!
@subsection They won't work!




@node Daily Auto-tester
@section Daily Auto-tester

We run the script

@example
scripts/dailytest.sh
@end example

@noindent
every day.  This script performs a few tasks:

@enumerate
@item
Exports a clean copy of the source tree from svn.

@item
Builds the tree using autotools.

@item
Runs the sanity tests.

@item
Runs the coffee tests.

@item
Runs make distcheck.  TODO: not currently implemented.

@end enumerate

An email is sent to some developers with the results of these tests.


