find_path(MAXSDK_MAX_INCLUDE_DIR c74support/max-includes)
find_path(MAXSDK_MSP_INCLUDE_DIR c74support/msp-includes)
find_library(MAXSDK_API_LIBRARY NAMES c74support/max-includes/MaxAPI.lib)
find_library(MAXSDK_CRT_LIBRARY NAMES c74support/max-includes/maxcrt.lib)
find_library(MAXSDK_AUDIO_LIBRARY NAMES c74support/msp-includes/MaxAudio.lib)

if (MAXSDK_MAX_INCLUDE_DIR AND MAXSDK_CRT_LIBRARY AND MAXSDK_MSP_INCLUDE_DIR AND MAXSDK_API_LIBRARY AND MAXSDK_AUDIO_LIBRARY)
	set(MAXSDK_FOUND TRUE)
endif (MAXSDK_MAX_INCLUDE_DIR AND MAXSDK_CRT_LIBRARY AND MAXSDK_MSP_INCLUDE_DIR AND MAXSDK_API_LIBRARY AND MAXSDK_AUDIO_LIBRARY)

if (MAXSDK_FOUND)
	if (NOT MAXSDK_FIND_QUIETLY)
		message (STATUS "Found MAXSDK: ${MAXSDK_API_LIBRARY}; ${MAXSDK_CRT_LIBRARY}; ${MAXSDK_AUDIO_LIBRARY}")
	endif (NOT MAXSDK_FIND_QUIETLY)
else (MAXSDK_FOUND)
	if (MAXSDK_FIND_REQUIRED)
		message (FATAL_ERROR "Couldn't find: MAXSDK")
	endif (MAXSDK_FIND_REQUIRED)
endif (MAXSDK_FOUND)


