set( CPACK_GENERATOR TBZ2)
set( CPACK_SOURCE_GENERATOR TBZ2)

SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Music Analysis Retrieval
and Synthesis for Audio Signals")
SET(CPACK_PACKAGE_VENDOR "Marsyas Development Team")
#SET(CPACK_PACKAGE_DESCRIPTION_FILE
#"${CMAKE_CURRENT_SOURCE_DIR}/ReadMe.txt")
SET(CPACK_RESOURCE_FILE_LICENSE
  "${CMAKE_SOURCE_DIR}/../COPYING")
SET(CPACK_GENERATOR "TGZ")
SET(CPACK_SOURCE_GENERATOR "TGZ")
SET(CPACK_PACKAGE_VERSION_MAJOR ${MARSYAS_VERSION_MAJOR})
SET(CPACK_PACKAGE_VERSION_MINOR ${MARSYAS_VERSION_MINOR})
SET(CPACK_PACKAGE_VERSION_PATCH ${MARSYAS_VERSION_PATCH})

SET(CPACK_SOURCE_PACKAGE_FILE_NAME
  "marsyas-${MARSYAS_VERSION_MAJOR}.${MARSYAS_VERSION_MINOR}.${MARSYAS_VERSION_PATCH}")

SET(CPACK_PACKAGE_INSTALL_DIRECTORY
  "marsyas-${MARSYAS_VERSION_MAJOR}.${MARSYAS_VERSION_MINOR}.${MARSYAS_VERSION_PATCH}")

#IF(WIN32 AND NOT UNIX)
  # There is a bug in NSI that does not handle full unix paths
  # properly. Make
  # sure there is at least one set of four (4) backlasshes.
#  SET(CPACK_PACKAGE_ICON
#"${CMake_SOURCE_DIR}/Utilities/Release\\\\InstallIcon.bmp")
#  SET(CPACK_NSIS_INSTALLED_ICON_NAME "bin\\\\MyExecutable.exe")
#  SET(CPACK_NSIS_DISPLAY_NAME "${CPACK_PACKAGE_INSTALL_DIRECTORY}
#My Famous Project")
#  SET(CPACK_NSIS_HELP_LINK
#"http:\\\\\\\\www.my-project-home-page.org")
#  SET(CPACK_NSIS_URL_INFO_ABOUT
#"http:\\\\\\\\www.my-personal-home-page.com")
#  SET(CPACK_NSIS_CONTACT "me@my-personal-home-page.com")
#  SET(CPACK_NSIS_MODIFY_PATH ON)
#ELSE(WIN32 AND NOT UNIX)
#  SET(CPACK_STRIP_FILES "bin/MyExecutable")
#  SET(CPACK_SOURCE_STRIP_FILES "")
#ENDIF(WIN32 AND NOT UNIX)
#SET(CPACK_PACKAGE_EXECUTABLES "MyExecutable" "My Executable")



