SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Music Analysis Retrieval and Synthesis for Audio Signals")
SET(CPACK_PACKAGE_VENDOR "Marsyas Development Team")
#SET(CPACK_PACKAGE_DESCRIPTION_FILE
#"${CMAKE_CURRENT_SOURCE_DIR}/ReadMe.txt")
SET(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/COPYING")
SET(CPACK_PACKAGE_VERSION_MAJOR ${MARSYAS_VERSION_MAJOR})
SET(CPACK_PACKAGE_VERSION_MINOR ${MARSYAS_VERSION_MINOR})
SET(CPACK_PACKAGE_VERSION_PATCH ${MARSYAS_VERSION_PATCH})

SET(CPACK_SOURCE_PACKAGE_FILE_NAME
  "marsyas-${MARSYAS_VERSION_MAJOR}.${MARSYAS_VERSION_MINOR}.${MARSYAS_VERSION_PATCH}")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY
  "marsyas-${MARSYAS_VERSION_MAJOR}.${MARSYAS_VERSION_MINOR}.${MARSYAS_VERSION_PATCH}")

if(UNIX)
  SET(CPACK_GENERATOR "TGZ")
  SET(CPACK_SOURCE_GENERATOR "TGZ")
elseif(WIN32)
  #configure_file("${CMAKE_SOURCE_DIR}/COPYING" "licence.txt" COPYONLY)
  #set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_BINARY_DIR}/licence.txt")
  #SET(CPACK_GENERATOR "WIX")
  SET(CPACK_GENERATOR ZIP)
endif()

include(CPack)
