set(CTEST_BUILD_NAME "Complete")
set(CTEST_BUILD_CONFIGURATION "Debug")
set(CTEST_BUILD_OPTIONS
  -DWITH_CPP11=ON
  -DWITH_QT=ON
  -DWITH_OPENGL=ON
  -DWITH_SWIG=ON
  -DWITH_SWIG_PYTHON=ON
  -DMARSYAS_AUDIOIO=ON
  -DMARSYAS_MIDIIO=ON
)
