#! /bin/sh

# libpng-config
# provides configuration info for libpng.

# Copyright (C) 2002, 2004, 2006, 2007 Glenn Randers-Pehrson
# For conditions of distribution and use, see copyright notice in png.h

# Modeled after libxml-config.

version="1.2.35"
prefix="/usr/local"
exec_prefix="/usr/local"
libdir="/usr/local/lib"
includedir="/usr/local/include/libpng12"
libs="-lpng12"
all_libs="-lpng12 "
I_opts="-I/usr/local/include"
L_opts="-L/usr/local/lib"
R_opts=""
cppflags=""
ccopts=""
ldopts=""

usage()
{
    cat <<EOF
Usage: $0 [OPTION] ...

Known values for OPTION are:

  --prefix        print libpng prefix
  --libdir        print path to directory containing library
  --libs          print library linking information
  --ccopts        print compiler options
  --cppflags      print pre-processor flags
  --cflags        print preprocessor flags, I_opts, and compiler options
  --I_opts        print "-I" include options
  --L_opts        print linker "-L" flags for dynamic linking
  --R_opts        print dynamic linker "-R" or "-rpath" flags
  --ldopts        print linker options
  --ldflags       print linker flags (ldopts, L_opts, R_opts, and libs)
  --static        revise subsequent outputs for static linking
  --help          print this help and exit
  --version       print version information
EOF

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

while test $# -gt 0; do
    case "$1" in

    --prefix)
        echo /usr/local
        ;;

    --version)
        echo 
        exit 0
        ;;

    --help)
        usage 0
        ;;

    --ccopts)
        echo 
        ;;

    --cppflags)
        echo 
        ;;

    --cflags)
        echo   
        ;;

    --libdir)
        echo /usr/local/lib
        ;;

    --libs)
        echo 
        ;;

    --I_opts)
        echo 
        ;;

    --L_opts)
        echo 
        ;;

    --R_opts)
        echo 
        ;;

    --ldopts)
    	echo 
	;;

    --ldflags)
        echo    
        ;;

    --static)
        R_opts=""
	libs=
        ;;

    *)
        usage
        exit 1
        ;;
    esac
    shift
done

exit 0
