#!/usr/bin/env python

from math import sqrt
import argparse
from marsyas import *
from os import path, mkdir, makedirs
import subprocess

################################################################################
# Parse Command-line Arguments
#
parser = argparse.ArgumentParser(description='Extract chroma features for classifier training.')
parser.add_argument('filelist', metavar='filelist', type=str, nargs=1,
                    help='List of files to extract chroma features from.')
parser.add_argument('scratchdir', metavar='scratchdir', type=str, nargs=1,
                    help='Output directory.')
args = parser.parse_args()

################################################################################
# Process
#
try: 
    makedirs(args.scratchdir[0])
except:
    None

try:
    filelist = open(args.filelist[0], 'r')
except:
    print("Could not open " + args.filelist[0] + ".")
    exit(1)

for filename in filelist:
    print("Extracting training data for " + filename.strip())
    subprocess.call(['./scripts/extractTrainingData.py', filename.strip(), filename.strip() + '.txt', args.scratchdir[0], '--resonance', '50'])
filelist.close();

