// Generated by Bisonc++ V4.04.01 on Wed, 18 Dec 2013 13:12:05 -0800

// $insert class.ih
#include "parser_impl.h"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {276, 0}, // 1: input ->  <empty>
     {276, 2}, // 2: input ->  directives actor_instance
     {277, 0}, // 3: directives ->  <empty>
     {277, 2}, // 4: directives ->  directives directive_line
     {279, 3}, // 5: directive_line ('#') ->  '#' directive '\x0a'
     {280, 1}, // 6: directive ->  include_directive
     {281, 2}, // 7: include_directive (INCLUDE) ->  INCLUDE directive_arg
     {281, 4}, // 8: include_directive (INCLUDE) ->  INCLUDE directive_arg AS id
     {278, 2}, // 9: actor_instance ->  actor_instance_decl actor_def
     {286, 2}, // 10: actor_prototype ->  actor_prototype_decl actor_def
     {284, 1}, // 11: actor_instance_decl ->  id
     {284, 3}, // 12: actor_instance_decl (':') ->  id ':' id
     {287, 3}, // 13: actor_prototype_decl (':') ->  id ':' id
     {287, 3}, // 14: actor_prototype_decl (':') ->  id ':' string
     {285, 0}, // 15: actor_def ->  <empty>
     {285, 3}, // 16: actor_def ('{') ->  '{' actor_def_list '}'
     {289, 0}, // 17: actor_def_list ->  <empty>
     {289, 2}, // 18: actor_def_list ->  actor_def_list actor_def_element
     {290, 2}, // 19: actor_def_element (ARROW) ->  ARROW actor_instance
     {290, 2}, // 20: actor_def_element ('~') ->  '~' actor_prototype
     {290, 1}, // 21: actor_def_element ->  control
     {290, 2}, // 22: actor_def_element ('+') ->  '+' control
     {290, 1}, // 23: actor_def_element ->  state
     {291, 3}, // 24: control ('=') ->  path '=' control_value
     {294, 1}, // 25: control_value ->  bool
     {294, 1}, // 26: control_value ->  int
     {294, 1}, // 27: control_value ->  real
     {294, 1}, // 28: control_value ->  matrix
     {294, 1}, // 29: control_value ->  string
     {294, 1}, // 30: control_value ->  path
     {294, 3}, // 31: control_value ('(') ->  '(' operation ')'
     {292, 8}, // 32: state (WHEN) ->  WHEN '(' operation ')' '{' state_def '}' else_state
     {301, 0}, // 33: else_state ->  <empty>
     {301, 4}, // 34: else_state (ELSE) ->  ELSE '{' state_def '}'
     {300, 0}, // 35: state_def ->  <empty>
     {300, 2}, // 36: state_def ->  state_def control
     {298, 3}, // 37: matrix ('[') ->  '[' matrix_contents ']'
     {302, 0}, // 38: matrix_contents ->  <empty>
     {302, 1}, // 39: matrix_contents ->  matrix_row
     {302, 3}, // 40: matrix_contents (';') ->  matrix_contents ';' matrix_row
     {303, 1}, // 41: matrix_row ->  matrix_value
     {303, 3}, // 42: matrix_row (',') ->  matrix_row ',' matrix_value
     {304, 1}, // 43: matrix_value ->  real
     {304, 1}, // 44: matrix_value ->  int
     {299, 1}, // 45: operation ->  operation_value
     {299, 3}, // 46: operation (COMPARE) ->  operation compare operation
     {299, 3}, // 47: operation (MATH1) ->  operation math1 operation
     {299, 3}, // 48: operation (MATH2) ->  operation math2 operation
     {299, 3}, // 49: operation ('(') ->  '(' operation ')'
     {306, 1}, // 50: compare (EQ) ->  EQ
     {306, 1}, // 51: compare (NEQ) ->  NEQ
     {306, 1}, // 52: compare (LESS) ->  LESS
     {306, 1}, // 53: compare (MORE) ->  MORE
     {307, 1}, // 54: math1 ('+') ->  '+'
     {307, 1}, // 55: math1 ('-') ->  '-'
     {308, 1}, // 56: math2 ('*') ->  '*'
     {308, 1}, // 57: math2 ('/') ->  '/'
     {305, 1}, // 58: operation_value ->  bool
     {305, 1}, // 59: operation_value ->  int
     {305, 1}, // 60: operation_value ->  real
     {305, 1}, // 61: operation_value ->  matrix
     {305, 1}, // 62: operation_value ->  string
     {305, 1}, // 63: operation_value ->  path
     {295, 1}, // 64: bool (BOOL) ->  BOOL
     {296, 1}, // 65: int (INT) ->  INT
     {297, 1}, // 66: real (REAL) ->  REAL
     {288, 1}, // 67: string (STRING) ->  STRING
     {283, 1}, // 68: id (ID) ->  ID
     {293, 1}, // 69: path ->  id
     {293, 1}, // 70: path (PATH) ->  PATH
     {282, 1}, // 71: directive_arg (DIRECTIVE_ARG) ->  DIRECTIVE_ARG
     {309, 1}, // 72: input_$ ->  input
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_DEF}, {  4} },              
    { {     276}, {  1} }, // input     
    { {     277}, {  2} }, // directives
    { {   _EOF_}, { -1} }, // _EOF_     
    { {       0}, { -3} },              
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, { 7} },                       
    { {       278}, { 3} }, // actor_instance     
    { {       279}, { 4} }, // directive_line     
    { {       284}, { 5} }, // actor_instance_decl
    { {        35}, { 6} }, // '#'                
    { {       283}, { 7} }, // id                 
    { {       261}, { 8} }, // ID                 
    { {         0}, { 0} },                       
};

SR__ s_3[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_5[] =
{
    { { REQ_DEF}, {   3} },             
    { {     285}, {   9} }, // actor_def
    { {     123}, {  10} }, // '{'      
    { {       0}, { -15} },             
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, {  4} },                     
    { {       280}, { 11} }, // directive        
    { {       281}, { 12} }, // include_directive
    { {       266}, { 13} }, // INCLUDE          
    { {         0}, {  0} },                     
};

SR__ s_7[] =
{
    { { REQ_DEF}, {   2} },       
    { {      58}, {  14} }, // ':'
    { {       0}, { -11} },       
};

SR__ s_8[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -68} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_10[] =
{
    { { DEF_RED}, {   2} },                  
    { {     289}, {  15} }, // actor_def_list
    { {       0}, { -17} },                  
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {        10}, { 16} }, // '\x0a'
    { {         0}, {  0} },          
};

SR__ s_12[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  3} },                 
    { {       282}, { 17} }, // directive_arg
    { {       268}, { 18} }, // DIRECTIVE_ARG
    { {         0}, {  0} },                 
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  3} },      
    { {       283}, { 19} }, // id
    { {       261}, {  8} }, // ID
    { {         0}, {  0} },      
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, { 13} },                     
    { {       125}, { 20} }, // '}'              
    { {       290}, { 21} }, // actor_def_element
    { {       263}, { 22} }, // ARROW            
    { {       126}, { 23} }, // '~'              
    { {       291}, { 24} }, // control          
    { {        43}, { 25} }, // '+'              
    { {       292}, { 26} }, // state            
    { {       293}, { 27} }, // path             
    { {       264}, { 28} }, // WHEN             
    { {       283}, { 29} }, // id               
    { {       262}, { 30} }, // PATH             
    { {       261}, {  8} }, // ID               
    { {         0}, {  0} },                     
};

SR__ s_16[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_17[] =
{
    { { REQ_DEF}, {  2} },      
    { {     267}, { 31} }, // AS
    { {       0}, { -7} },      
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -71} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_20[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  5} },                       
    { {       278}, { 32} }, // actor_instance     
    { {       284}, {  5} }, // actor_instance_decl
    { {       283}, {  7} }, // id                 
    { {       261}, {  8} }, // ID                 
    { {         0}, {  0} },                       
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  5} },                        
    { {       286}, { 33} }, // actor_prototype     
    { {       287}, { 34} }, // actor_prototype_decl
    { {       283}, { 35} }, // id                  
    { {       261}, {  8} }, // ID                  
    { {         0}, {  0} },                        
};

SR__ s_24[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  6} },           
    { {       291}, { 36} }, // control
    { {       293}, { 27} }, // path   
    { {       283}, { 29} }, // id     
    { {       262}, { 30} }, // PATH   
    { {       261}, {  8} }, // ID     
    { {         0}, {  0} },           
};

SR__ s_26[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        61}, { 37} }, // '='
    { {         0}, {  0} },       
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 38} }, // '('
    { {         0}, {  0} },       
};

SR__ s_29[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -69} }, 
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -70} }, 
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  3} },      
    { {       283}, { 39} }, // id
    { {       261}, {  8} }, // ID
    { {         0}, {  0} },      
};

SR__ s_32[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_34[] =
{
    { { REQ_DEF}, {   3} },             
    { {     285}, {  40} }, // actor_def
    { {     123}, {  10} }, // '{'      
    { {       0}, { -15} },             
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        58}, { 41} }, // ':'
    { {         0}, {  0} },       
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, { 17} },                 
    { {       294}, { 42} }, // control_value
    { {       295}, { 43} }, // bool         
    { {       296}, { 44} }, // int          
    { {       297}, { 45} }, // real         
    { {       298}, { 46} }, // matrix       
    { {       288}, { 47} }, // string       
    { {       293}, { 48} }, // path         
    { {        40}, { 49} }, // '('          
    { {       260}, { 50} }, // BOOL         
    { {       257}, { 51} }, // INT          
    { {       258}, { 52} }, // REAL         
    { {        91}, { 53} }, // '['          
    { {       259}, { 54} }, // STRING       
    { {       283}, { 29} }, // id           
    { {       262}, { 30} }, // PATH         
    { {       261}, {  8} }, // ID           
    { {         0}, {  0} },                 
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, { 18} },                   
    { {       299}, { 55} }, // operation      
    { {       305}, { 56} }, // operation_value
    { {        40}, { 57} }, // '('            
    { {       295}, { 58} }, // bool           
    { {       296}, { 59} }, // int            
    { {       297}, { 60} }, // real           
    { {       298}, { 61} }, // matrix         
    { {       288}, { 62} }, // string         
    { {       293}, { 63} }, // path           
    { {       260}, { 50} }, // BOOL           
    { {       257}, { 51} }, // INT            
    { {       258}, { 52} }, // REAL           
    { {        91}, { 53} }, // '['            
    { {       259}, { 54} }, // STRING         
    { {       283}, { 29} }, // id             
    { {       262}, { 30} }, // PATH           
    { {       261}, {  8} }, // ID             
    { {         0}, {  0} },                   
};

SR__ s_39[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  5} },          
    { {       283}, { 64} }, // id    
    { {       288}, { 65} }, // string
    { {       261}, {  8} }, // ID    
    { {       259}, { 54} }, // STRING
    { {         0}, {  0} },          
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_44[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_45[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_47[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_48[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, { 18} },                   
    { {       299}, { 66} }, // operation      
    { {       305}, { 56} }, // operation_value
    { {        40}, { 57} }, // '('            
    { {       295}, { 58} }, // bool           
    { {       296}, { 59} }, // int            
    { {       297}, { 60} }, // real           
    { {       298}, { 61} }, // matrix         
    { {       288}, { 62} }, // string         
    { {       293}, { 63} }, // path           
    { {       260}, { 50} }, // BOOL           
    { {       257}, { 51} }, // INT            
    { {       258}, { 52} }, // REAL           
    { {        91}, { 53} }, // '['            
    { {       259}, { 54} }, // STRING         
    { {       283}, { 29} }, // id             
    { {       262}, { 30} }, // PATH           
    { {       261}, {  8} }, // ID             
    { {         0}, {  0} },                   
};

SR__ s_50[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -64} }, 
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -65} }, 
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -66} }, 
};

SR__ s_53[] =
{
    { { REQ_DEF}, {   8} },                   
    { {     302}, {  67} }, // matrix_contents
    { {     303}, {  68} }, // matrix_row     
    { {     304}, {  69} }, // matrix_value   
    { {     297}, {  70} }, // real           
    { {     296}, {  71} }, // int            
    { {     258}, {  52} }, // REAL           
    { {     257}, {  51} }, // INT            
    { {       0}, { -38} },                   
};

SR__ s_54[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -67} }, 
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, { 13} },           
    { {        41}, { 72} }, // ')'    
    { {       306}, { 73} }, // compare
    { {       307}, { 74} }, // math1  
    { {       308}, { 75} }, // math2  
    { {       269}, { 76} }, // EQ     
    { {       270}, { 77} }, // NEQ    
    { {       271}, { 78} }, // LESS   
    { {       272}, { 79} }, // MORE   
    { {        43}, { 80} }, // '+'    
    { {        45}, { 81} }, // '-'    
    { {        42}, { 82} }, // '*'    
    { {        47}, { 83} }, // '/'    
    { {         0}, {  0} },           
};

SR__ s_56[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, { 18} },                   
    { {       299}, { 84} }, // operation      
    { {       305}, { 56} }, // operation_value
    { {        40}, { 57} }, // '('            
    { {       295}, { 58} }, // bool           
    { {       296}, { 59} }, // int            
    { {       297}, { 60} }, // real           
    { {       298}, { 61} }, // matrix         
    { {       288}, { 62} }, // string         
    { {       293}, { 63} }, // path           
    { {       260}, { 50} }, // BOOL           
    { {       257}, { 51} }, // INT            
    { {       258}, { 52} }, // REAL           
    { {        91}, { 53} }, // '['            
    { {       259}, { 54} }, // STRING         
    { {       283}, { 29} }, // id             
    { {       262}, { 30} }, // PATH           
    { {       261}, {  8} }, // ID             
    { {         0}, {  0} },                   
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -59} }, 
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -61} }, 
};

SR__ s_62[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -62} }, 
};

SR__ s_63[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -63} }, 
};

SR__ s_64[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_65[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, { 13} },           
    { {        41}, { 85} }, // ')'    
    { {       306}, { 73} }, // compare
    { {       307}, { 74} }, // math1  
    { {       308}, { 75} }, // math2  
    { {       269}, { 76} }, // EQ     
    { {       270}, { 77} }, // NEQ    
    { {       271}, { 78} }, // LESS   
    { {       272}, { 79} }, // MORE   
    { {        43}, { 80} }, // '+'    
    { {        45}, { 81} }, // '-'    
    { {        42}, { 82} }, // '*'    
    { {        47}, { 83} }, // '/'    
    { {         0}, {  0} },           
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        93}, { 86} }, // ']'
    { {        59}, { 87} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_68[] =
{
    { { REQ_DEF}, {   2} },       
    { {      44}, {  88} }, // ','
    { {       0}, { -39} },       
};

SR__ s_69[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_71[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       123}, { 89} }, // '{'
    { {         0}, {  0} },       
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, { 18} },                   
    { {       299}, { 90} }, // operation      
    { {       305}, { 56} }, // operation_value
    { {        40}, { 57} }, // '('            
    { {       295}, { 58} }, // bool           
    { {       296}, { 59} }, // int            
    { {       297}, { 60} }, // real           
    { {       298}, { 61} }, // matrix         
    { {       288}, { 62} }, // string         
    { {       293}, { 63} }, // path           
    { {       260}, { 50} }, // BOOL           
    { {       257}, { 51} }, // INT            
    { {       258}, { 52} }, // REAL           
    { {        91}, { 53} }, // '['            
    { {       259}, { 54} }, // STRING         
    { {       283}, { 29} }, // id             
    { {       262}, { 30} }, // PATH           
    { {       261}, {  8} }, // ID             
    { {         0}, {  0} },                   
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, { 18} },                   
    { {       299}, { 91} }, // operation      
    { {       305}, { 56} }, // operation_value
    { {        40}, { 57} }, // '('            
    { {       295}, { 58} }, // bool           
    { {       296}, { 59} }, // int            
    { {       297}, { 60} }, // real           
    { {       298}, { 61} }, // matrix         
    { {       288}, { 62} }, // string         
    { {       293}, { 63} }, // path           
    { {       260}, { 50} }, // BOOL           
    { {       257}, { 51} }, // INT            
    { {       258}, { 52} }, // REAL           
    { {        91}, { 53} }, // '['            
    { {       259}, { 54} }, // STRING         
    { {       283}, { 29} }, // id             
    { {       262}, { 30} }, // PATH           
    { {       261}, {  8} }, // ID             
    { {         0}, {  0} },                   
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, { 18} },                   
    { {       299}, { 92} }, // operation      
    { {       305}, { 56} }, // operation_value
    { {        40}, { 57} }, // '('            
    { {       295}, { 58} }, // bool           
    { {       296}, { 59} }, // int            
    { {       297}, { 60} }, // real           
    { {       298}, { 61} }, // matrix         
    { {       288}, { 62} }, // string         
    { {       293}, { 63} }, // path           
    { {       260}, { 50} }, // BOOL           
    { {       257}, { 51} }, // INT            
    { {       258}, { 52} }, // REAL           
    { {        91}, { 53} }, // '['            
    { {       259}, { 54} }, // STRING         
    { {       283}, { 29} }, // id             
    { {       262}, { 30} }, // PATH           
    { {       261}, {  8} }, // ID             
    { {         0}, {  0} },                   
};

SR__ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_77[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_78[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_82[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_84[] =
{
    { { REQ_TOKEN}, { 13} },           
    { {        41}, { 93} }, // ')'    
    { {       306}, { 73} }, // compare
    { {       307}, { 74} }, // math1  
    { {       308}, { 75} }, // math2  
    { {       269}, { 76} }, // EQ     
    { {       270}, { 77} }, // NEQ    
    { {       271}, { 78} }, // LESS   
    { {       272}, { 79} }, // MORE   
    { {        43}, { 80} }, // '+'    
    { {        45}, { 81} }, // '-'    
    { {        42}, { 82} }, // '*'    
    { {        47}, { 83} }, // '/'    
    { {         0}, {  0} },           
};

SR__ s_85[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_86[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, {  7} },                
    { {       303}, { 94} }, // matrix_row  
    { {       304}, { 69} }, // matrix_value
    { {       297}, { 70} }, // real        
    { {       296}, { 71} }, // int         
    { {       258}, { 52} }, // REAL        
    { {       257}, { 51} }, // INT         
    { {         0}, {  0} },                
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, {  6} },                
    { {       304}, { 95} }, // matrix_value
    { {       297}, { 70} }, // real        
    { {       296}, { 71} }, // int         
    { {       258}, { 52} }, // REAL        
    { {       257}, { 51} }, // INT         
    { {         0}, {  0} },                
};

SR__ s_89[] =
{
    { { DEF_RED}, {   2} },             
    { {     300}, {  96} }, // state_def
    { {       0}, { -35} },             
};

SR__ s_90[] =
{
    { { REQ_DEF}, {   4} },           
    { {     306}, {  73} }, // compare
    { {     307}, {  74} }, // math1  
    { {     308}, {  75} }, // math2  
    { {       0}, { -46} },           
};

SR__ s_91[] =
{
    { { REQ_DEF}, {   4} },           
    { {     306}, {  73} }, // compare
    { {     307}, {  74} }, // math1  
    { {     308}, {  75} }, // math2  
    { {       0}, { -47} },           
};

SR__ s_92[] =
{
    { { REQ_DEF}, {   4} },           
    { {     306}, {  73} }, // compare
    { {     307}, {  74} }, // math1  
    { {     308}, {  75} }, // math2  
    { {       0}, { -48} },           
};

SR__ s_93[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_94[] =
{
    { { REQ_DEF}, {   2} },       
    { {      44}, {  88} }, // ','
    { {       0}, { -40} },       
};

SR__ s_95[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_96[] =
{
    { { REQ_TOKEN}, {  7} },           
    { {       125}, { 97} }, // '}'    
    { {       291}, { 98} }, // control
    { {       293}, { 27} }, // path   
    { {       283}, { 29} }, // id     
    { {       262}, { 30} }, // PATH   
    { {       261}, {  8} }, // ID     
    { {         0}, {  0} },           
};

SR__ s_97[] =
{
    { { REQ_DEF}, {   3} },              
    { {     301}, {  99} }, // else_state
    { {     265}, { 100} }, // ELSE      
    { {       0}, { -33} },              
};

SR__ s_98[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_99[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_100[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {       123}, { 101} }, // '{'
    { {         0}, {   0} },       
};

SR__ s_101[] =
{
    { { DEF_RED}, {   2} },             
    { {     300}, { 102} }, // state_def
    { {       0}, { -35} },             
};

SR__ s_102[] =
{
    { { REQ_TOKEN}, {   7} },           
    { {       125}, { 103} }, // '}'    
    { {       291}, {  98} }, // control
    { {       293}, {  27} }, // path   
    { {       283}, {  29} }, // id     
    { {       262}, {  30} }, // PATH   
    { {       261}, {   8} }, // ID     
    { {         0}, {   0} },           
};

SR__ s_103[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,
};

} // anonymous namespace ends


// $insert namespace-open
namespace Marsyas
{

// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 2:
#line 20 "parser.y"
        { d_directives = d_vsp__[-1]; d_actor = d_vsp__[0]; }
        break;

        case 4:
#line 26 "parser.y"
        {
         d_vsp__[-1].components.push_back(d_vsp__[0]);
         d_val__ = d_vsp__[-1];
        }
        break;

        case 5:
#line 34 "parser.y"
        {
        d_val__ = d_vsp__[-1];
        }
        break;

        case 6:
#line 40 "parser.y"
        { d_val__ = d_vsp__[0]; d_val__.tag = INCLUDE_DIRECTIVE; }
        break;

        case 7:
#line 45 "parser.y"
        {
        d_val__ = node();
        d_val__.components = {d_vsp__[0]};
        }
        break;

        case 8:
#line 51 "parser.y"
        {
        d_val__ = node();
        d_val__.components = {d_vsp__[-2], d_vsp__[0]};
        }
        break;

        case 9:
#line 60 "parser.y"
        {
         d_val__ = node();
         d_val__.tag = ACTOR_NODE;
         d_val__.components = { d_vsp__[-1].components[0], d_vsp__[-1].components[1], d_vsp__[0] };
        }
        break;

        case 10:
#line 69 "parser.y"
        {
         d_val__ = node();
         d_val__.tag = PROTOTYPE_NODE;
         d_val__.components = { d_vsp__[-1].components[0], d_vsp__[-1].components[1], d_vsp__[0] };
        }
        break;

        case 11:
#line 78 "parser.y"
        { d_val__ = node(); d_val__.components = {node(), d_vsp__[0]}; }
        break;

        case 12:
#line 81 "parser.y"
        { d_val__ = node(); d_val__.components = {d_vsp__[-2], d_vsp__[0]}; }
        break;

        case 13:
#line 87 "parser.y"
        { d_val__ = node(); d_val__.components = {d_vsp__[-2], d_vsp__[0]}; }
        break;

        case 14:
#line 90 "parser.y"
        { d_val__ = node(); d_val__.components = {d_vsp__[-2], d_vsp__[0]}; }
        break;

        case 16:
#line 96 "parser.y"
        { d_val__ = d_vsp__[-1]; }
        break;

        case 18:
#line 103 "parser.y"
        {
         d_vsp__[-1].components.push_back(d_vsp__[0]);
         d_val__ = d_vsp__[-1];
        }
        break;

        case 19:
#line 111 "parser.y"
        { d_val__ = d_vsp__[0]; }
        break;

        case 20:
#line 113 "parser.y"
        { d_val__ = d_vsp__[0]; }
        break;

        case 22:
#line 118 "parser.y"
        {
         d_vsp__[0].components[0].s = std::string("+") + d_vsp__[0].components[0].s;
         d_val__ = d_vsp__[0];
        }
        break;

        case 24:
#line 127 "parser.y"
        {
         d_val__ = node();
         d_val__.tag = CONTROL_NODE;
         d_val__.components = { std::move(d_vsp__[-2]), std::move(d_vsp__[0]) };
        #ifdef MARSYAS_DEBUG_SCRIPT
         std::cout << "control:"
         << " '" << d_val__.components[0].s << "'"
         << " '" << d_val__.components[1].s << "'"
         << std::endl;
        #endif
         }
        break;

        case 31:
#line 144 "parser.y"
        {
         d_val__ = d_vsp__[-1];
        }
        break;

        case 32:
#line 151 "parser.y"
        {
         d_val__ = node();
         d_val__.tag = STATE_NODE;
         d_val__.components.push_back(d_vsp__[-5]);
         d_val__.components.push_back(d_vsp__[-2]);
         d_val__.components.push_back(d_vsp__[0]);
        }
        break;

        case 34:
#line 163 "parser.y"
        {
         d_val__ = d_vsp__[-1];
        }
        break;

        case 36:
#line 171 "parser.y"
        {
         d_vsp__[-1].components.push_back(d_vsp__[0]);
         d_val__ = d_vsp__[-1];
        }
        break;

        case 37:
#line 179 "parser.y"
        {
         d_val__ = d_vsp__[-1];
         d_val__.tag = MATRIX_NODE;
        }
        break;

        case 39:
#line 189 "parser.y"
        {
         d_val__ = node();
         d_val__.components.push_back(d_vsp__[0]);
        }
        break;

        case 40:
#line 195 "parser.y"
        {
         d_val__ = d_vsp__[-2];
         d_val__.components.push_back(d_vsp__[0]);
        }
        break;

        case 41:
#line 203 "parser.y"
        {
         d_val__ = node();
         d_val__.components.push_back(d_vsp__[0]);
        }
        break;

        case 42:
#line 209 "parser.y"
        {
         d_val__ = d_vsp__[-2];
         d_val__.components.push_back(d_vsp__[0]);
        }
        break;

        case 46:
#line 222 "parser.y"
        { d_val__.set_operation(d_vsp__[-2], d_vsp__[-1].s, d_vsp__[0]); }
        break;

        case 47:
#line 225 "parser.y"
        { d_val__.set_operation(d_vsp__[-2], d_vsp__[-1].s, d_vsp__[0]); }
        break;

        case 48:
#line 228 "parser.y"
        { d_val__.set_operation(d_vsp__[-2], d_vsp__[-1].s, d_vsp__[0]); }
        break;

        case 49:
#line 230 "parser.y"
        { d_val__ = d_vsp__[-1]; }
        break;

        case 50:
#line 234 "parser.y"
        { d_val__ = d_scanner.matched(); }
        break;

        case 51:
#line 235 "parser.y"
        { d_val__ = d_scanner.matched(); }
        break;

        case 52:
#line 236 "parser.y"
        { d_val__ = d_scanner.matched(); }
        break;

        case 53:
#line 237 "parser.y"
        { d_val__ = d_scanner.matched(); }
        break;

        case 54:
#line 241 "parser.y"
        { d_val__ = d_scanner.matched(); }
        break;

        case 55:
#line 242 "parser.y"
        { d_val__ = d_scanner.matched(); }
        break;

        case 56:
#line 246 "parser.y"
        { d_val__ = d_scanner.matched(); }
        break;

        case 57:
#line 247 "parser.y"
        { d_val__ = d_scanner.matched(); }
        break;

        case 64:
#line 253 "parser.y"
        { d_val__ = d_scanner.bool_value(); }
        break;

        case 65:
#line 257 "parser.y"
        { d_val__ = d_scanner.int_value(); }
        break;

        case 66:
#line 261 "parser.y"
        { d_val__ = d_scanner.real_value(); }
        break;

        case 67:
#line 265 "parser.y"
        { d_val__ = d_scanner.string_value(); }
        break;

        case 68:
#line 269 "parser.y"
        { d_val__ = d_scanner.matched(); d_val__.tag = ID_NODE; }
        break;

        case 70:
#line 274 "parser.y"
        { d_val__ = d_scanner.matched(); d_val__.tag = ID_NODE; }
        break;

        case 71:
#line 278 "parser.y"
        { d_val__ = d_scanner.matched(); }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}


// $insert namespace-close
}


