// Generated by Flexc++ V1.05.00 on Sat, 30 Nov 2013 23:54:07 -0800

// $insert class_h
#include "scanner.h"

// $insert namespace-use
    // UN-comment the next using-declaration if you want to use
    // symbols from the namespace Marsyas without prefixing Marsyas::
//using namespace Marsyas;
