######################################################################
# Automatically generated by qmake (2.00a) Tue Apr 11 11:09:58 2006
######################################################################

include (../Qt4Apps.pri)
TEMPLATE = app
TARGET = MarxGLGraph
INCLUDEPATH += . ..
QT += opengl


# Input
HEADERS += MarxGLColorGraph.h TopPanelNew.h
SOURCES += main.cpp \
           MarxGLColorGraph.cpp \
           TopPanelNew.cpp
